#!/usr/bin/env bash
# =============================================================================
# Lilith Linux — Configure Chroot APT Sources for Lilith Repo
# =============================================================================
# Adds the Lilith Linux custom package repository to the chroot's apt sources.
# This enables 'apt install hellfire', 'apt install s8n-system', etc.
#
# Run as: sudo bash /home/aegon/lil-build/configure-chroot-apt-sources.sh
# =============================================================================
set -euo pipefail

CHROOT="/home/aegon/Lilith/custom-root"
REPO_ROOT="/home/aegon/lil-build/Lilith-Repo"
REPO_URL="https://packages.lilithlinux.org"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info() { echo -e "${GREEN}[✔]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
step() { echo -e "\n${BLUE}══${NC} $* ${BLUE}══${NC}"; }

[[ $EUID -eq 0 ]] || { echo "Run as root: sudo bash $0"; exit 1; }
[[ -d "$CHROOT" ]] || { echo "Chroot not found: $CHROOT"; exit 1; }

step "Configuring Lilith Repository in Chroot APT Sources"

# ── 1. Add Lilith repo as a .sources file (deb822 format) ────────────────────
SOURCES_DIR="$CHROOT/etc/apt/sources.list.d"
mkdir -p "$SOURCES_DIR"

# Clean up legacy .list file if it exists to prevent APT conflicts
if [[ -f "$SOURCES_DIR/lilith-linux.list" ]]; then
    rm -f "$SOURCES_DIR/lilith-linux.list"
    info "Removed legacy lilith-linux.list"
fi


cat > "$SOURCES_DIR/lilith-linux.sources" << EOF
# Lilith Linux Custom Package Repository
# Generated by configure-chroot-apt-sources.sh
# URL: ${REPO_URL}
#
# To update this repo on the installed system:
#   sudo apt update && sudo apt upgrade
# To install a Lilith package:
#   sudo apt install hellfire
#   sudo apt install s8n-system
#   sudo apt install vicinae

Types: deb
URIs: ${REPO_URL}
Suites: stable
Components: core xtra
Architectures: amd64
Signed-By: /usr/share/keyrings/lilith-archive-keyring.gpg
EOF
info "Lilith repo .sources entry written"


# ── 3. Install a placeholder keyring ─────────────────────────────────────────
# (In production, this would be the real GPG key — using trusted=yes for now)
KEYRING_DIR="$CHROOT/usr/share/keyrings"
mkdir -p "$KEYRING_DIR"

# Check if a real key exists in lil-build
if [[ -f "/home/aegon/lil-build/lilith-archive-keyring.gpg" ]]; then
    cp "/home/aegon/lil-build/lilith-archive-keyring.gpg" "$KEYRING_DIR/lilith-archive-keyring.gpg"
    info "Lilith GPG keyring installed"
else
    warn "No GPG key found at /home/aegon/lil-build/lilith-archive-keyring.gpg"
    warn "Using 'trusted=yes' in sources — acceptable for local/self-hosted repo"
    # Update the .sources file to use trusted=yes instead of Signed-By for now
    cat > "$SOURCES_DIR/lilith-linux.sources" << EOF
# Lilith Linux Custom Package Repository
# URL: ${REPO_URL}

Types: deb
URIs: ${REPO_URL}
Suites: stable
Components: core xtra
Architectures: amd64
Trusted: yes
EOF
fi

# ── 4. Also set up LOCAL file:// source for Cubic builds ─────────────────────
# When building in Cubic, the repo is available locally at the host path.
# We add a file:// source so packages can be installed directly from disk
# without needing the live internet URL.
REPO_ABS_PATH="$REPO_ROOT"
cat > "$SOURCES_DIR/lilith-local.list" << EOF
# Lilith Linux LOCAL Repository (for Cubic/chroot builds)
# Points to the locally built repo on the host system.
# This entry is automatically disabled on the installed system.
deb [arch=amd64 trusted=yes] file://${REPO_ABS_PATH} stable core xtra
EOF
info "Local file:// source written for Cubic builds"

# ── 5. Configure apt preferences to prefer Lilith repo ───────────────────────
mkdir -p "$CHROOT/etc/apt/preferences.d"
cat > "$CHROOT/etc/apt/preferences.d/lilith-priority.pref" << EOF
# Lilith Linux APT Preferences
# Prefer packages from the Lilith repo over Ubuntu upstream

Package: *
Pin: origin packages.lilithlinux.org
Pin-Priority: 900

Package: *
Pin: origin ""
Pin-Priority: 500
EOF
info "APT preferences configured (Lilith repo has priority 900)"

# ── 6. Write an apt.conf.d snippet to suppress cdrom errors ──────────────────
mkdir -p "$CHROOT/etc/apt/apt.conf.d"
cat > "$CHROOT/etc/apt/apt.conf.d/99-lilith-silence-cdrom" << 'EOF'
// Suppress cdrom source errors (irrelevant in installed system)
Acquire::cdrom::AutoDetect "false";
APT::Get::AllowUnauthenticated "false";
EOF
info "APT cdrom suppression configured"

# ── 7. Write a post-install apt sources cleanup script ───────────────────────
# This runs once on first boot to remove the local file:// source
FIRST_BOOT_DIR="$CHROOT/etc/profile.d"
cat > "$FIRST_BOOT_DIR/lilith-apt-setup.sh" << 'FIRSTBOOT'
#!/bin/bash
# Lilith Linux — First-boot APT source cleanup
# Removes the local file:// source and disables cdrom source after installation
LOCAL_LIST="/etc/apt/sources.list.d/lilith-local.list"
CDROM_LIST="/etc/apt/sources.list.d/cdrom.sources"

if [[ -f "$LOCAL_LIST" ]]; then
    rm -f "$LOCAL_LIST"
    echo "Lilith: Removed local repo source (system is now installed)"
fi

if [[ -f "$CDROM_LIST" ]]; then
    mv "$CDROM_LIST" "${CDROM_LIST}.disabled" 2>/dev/null || true
fi

# Remove this script after running once
rm -f /etc/profile.d/lilith-apt-setup.sh
FIRSTBOOT
chmod 644 "$CHROOT/etc/profile.d/lilith-apt-setup.sh"
info "First-boot APT cleanup script installed"

# ── 8. Mount and run apt-get update inside chroot to validate ─────────────────
step "Validating apt source configuration in chroot"

for fs in proc sys dev dev/pts run; do
    mount --bind "/$fs" "$CHROOT/$fs" 2>/dev/null || true
done
cat > "$CHROOT/usr/sbin/policy-rc.d" << 'EOF'
#!/bin/sh
exit 101
EOF
chmod +x "$CHROOT/usr/sbin/policy-rc.d"

cleanup() {
    rm -f "$CHROOT/usr/sbin/policy-rc.d" 2>/dev/null || true
    for fs in run dev/pts dev sys proc; do umount -lf "$CHROOT/$fs" 2>/dev/null || true; done
}
trap cleanup EXIT

# Disable cdrom for this validation run
CDROM_SRC="$CHROOT/etc/apt/sources.list.d/cdrom.sources"
[[ -f "$CDROM_SRC" ]] && mv "$CDROM_SRC" "${CDROM_SRC}.bak"

chroot "$CHROOT" /bin/bash << 'CHROOTEOF'
export DEBIAN_FRONTEND=noninteractive
echo ">>> Testing apt configuration..."
apt-get update 2>&1 | grep -E "^(Get|Hit|Ign|Err|W:)" | head -20 || true
echo ">>> Checking Lilith repo sources..."
apt-cache policy 2>/dev/null | grep -A2 "lilith" | head -10 || echo "  (Lilith remote repo not yet reachable — will be available on installed system)"
echo ">>> Checking local Lilith repo..."
apt-cache policy 2>/dev/null | grep -A2 "file://" | head -10 || true
echo ">>> Done."
CHROOTEOF

# Restore cdrom source
[[ -f "${CDROM_SRC}.bak" ]] && mv "${CDROM_SRC}.bak" "$CDROM_SRC"

step "=== APT Sources Configuration Summary ==="
echo ""
echo "  Files written to chroot:"
for f in "lilith-linux.sources" "lilith-linux.list" "lilith-local.list"; do
    [[ -f "$CHROOT/etc/apt/sources.list.d/$f" ]] && echo "    ✔ /etc/apt/sources.list.d/$f"
done
[[ -f "$CHROOT/etc/apt/preferences.d/lilith-priority.pref" ]] && echo "    ✔ /etc/apt/preferences.d/lilith-priority.pref"
[[ -f "$CHROOT/etc/apt/apt.conf.d/99-lilith-silence-cdrom" ]] && echo "    ✔ /etc/apt/apt.conf.d/99-lilith-silence-cdrom"
echo ""
echo "  APT source lines:"
echo "    deb [arch=amd64 trusted=yes] ${REPO_URL} stable core xtra"
echo "    deb [arch=amd64 trusted=yes] file://${REPO_ABS_PATH} stable core xtra"
echo ""
info "Chroot APT sources configured for Lilith Linux repository."
