#!/usr/bin/env python3
"""
generate-packages-toml.py
Generates packages.toml (simple flat manifest for s8n) from all known Lilith packages.
Run: python3 generate-packages-toml.py > packages.toml
"""

import sys

# ──────────────────────────────────────────────────────────────────────────────
# Package database — each dict becomes one [[packages]] entry
# Fields:
#   name        (str, required)
#   description (str, required)
#   version     (str, default "latest")
#   category    (str, default "xtra")  core | xtra | themes | ai | desktop
#   install     (str, required)        deb|cargo|github|tarball|appimage|script|git|npm|pip|apt|flatpak
#   url         (str)  — direct download URL (for deb/binary/appimage/tarball/script)
#   github      (str)  — "owner/repo" for GitHub API lookups
#   asset       (str)  — release asset filename pattern for GitHub installs
#   binary      (str)  — binary name for 'which' installed check
#   crate_name  (str)  — if different from name, for cargo installs
#   npm_name / pip_name / apt_name / flatpak_id (str)
#   install_cmd (str)  — shell command to run after git clone
# ──────────────────────────────────────────────────────────────────────────────

PACKAGES = [
    # ── Lilith First-Party ─────────────────────────────────────────────────────
    dict(name="s8n", description="Lilith unified system/package/file manager TUI",
         version="0.4.0", category="core", install="cargo", crate_name="s8n",
         github="BlancoBAM/S8n-System", binary="s8n"),
    dict(name="offerings", description="Unified package manager GUI for Lilith Linux",
         version="latest", category="core", install="github",
         github="BlancoBAM/Offerings", asset="amd64.deb", binary="offerings"),
    dict(name="tweakers", description="System optimization and tweaks GUI",
         version="latest", category="core", install="github",
         github="BlancoBAM/Tweakers", asset="amd64.deb", binary="tweakers"),
    dict(name="lilim", description="Lilith AI Assistant with persistent memory",
         version="latest", category="core", install="github",
         github="BlancoBAM/Lilim", asset="amd64.deb", binary="lilim"),
    dict(name="ouija-pad", description="Lilith default text editor",
         version="latest", category="core", install="github",
         github="BlancoBAM/Ouija-Pad", asset="amd64.deb", binary="ouija-pad"),
    dict(name="stake", description="Lilith Stake CLI package manager tool",
         version="latest", category="core", install="github",
         github="BlancoBAM/Stake", asset="amd64.deb", binary="stake"),
    dict(name="lilith-tts", description="Lilith Linux Text-to-Speech Engine daemon",
         version="latest", category="core", install="cargo",
         github="BlancoBAM/Lilith-TTS", binary="lilith-tts-daemon"),

    # ── Core Terminal Tools (mostly cargo crates or have .deb releases) ─────────
    dict(name="bat", description="A cat clone with syntax highlighting and Git integration",
         version="0.26.1", category="core", install="deb",
         url="https://github.com/sharkdp/bat/releases/download/v0.26.1/bat_0.26.1_amd64.deb",
         github="sharkdp/bat", asset="amd64.deb", binary="bat"),
    dict(name="lsd", description="Modern ls replacement with colors and icons",
         version="1.2.0", category="core", install="deb",
         url="https://github.com/lsd-rs/lsd/releases/download/v1.2.0/lsd_1.2.0_amd64.deb",
         github="lsd-rs/lsd", asset="amd64.deb", binary="lsd"),
    dict(name="eza", description="A modern replacement for ls",
         version="latest", category="core", install="github",
         github="eza-community/eza", asset="eza_x86_64-unknown-linux-gnu.tar.gz", binary="eza"),
    dict(name="nat", description="ls replacement with readable permissions",
         version="latest", category="xtra", install="cargo",
         github="willdoescode/nat", binary="nat"),
    dict(name="zoxide", description="Smart cd — learns your most frequent directories",
         version="0.9.9", category="core", install="deb",
         url="https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.9/zoxide_0.9.9-1_amd64.deb",
         github="ajeetdsouza/zoxide", asset="amd64.deb", binary="zoxide"),
    dict(name="fd", description="Fast user-friendly find alternative",
         version="latest", category="core", install="github",
         github="sharkdp/fd", asset="x86_64-unknown-linux-musl.tar.gz", binary="fd"),
    dict(name="ripgrep", description="Fast line-oriented search tool (rg)",
         version="latest", category="core", install="deb",
         github="BurntSushi/ripgrep", asset="amd64.deb", binary="rg"),
    dict(name="ripgrep-all", description="ripgrep over PDFs, Office docs, zip files (rga)",
         version="latest", category="core", install="github",
         github="phiresky/ripgrep-all", asset="x86_64-unknown-linux-musl.tar.gz", binary="rga"),
    dict(name="repgrep", description="Interactive ripgrep result replacement TUI",
         version="latest", category="xtra", install="cargo", crate_name="repgrep",
         github="acheronfail/repgrep", binary="rgr"),
    dict(name="delta", description="Syntax-highlighting pager for git diffs",
         version="latest", category="core", install="deb",
         github="dandavison/delta", asset="amd64.deb", binary="delta"),
    dict(name="difftastic", description="Structural diff tool that understands syntax",
         version="latest", category="xtra", install="cargo", crate_name="difftastic",
         github="Wilfred/difftastic", binary="difft"),
    dict(name="hyperfine", description="Command-line benchmarking tool",
         version="latest", category="core", install="deb",
         github="sharkdp/hyperfine", asset="amd64.deb", binary="hyperfine"),
    dict(name="hexyl", description="Command-line hex viewer",
         version="latest", category="xtra", install="deb",
         github="sharkdp/hexyl", asset="amd64.deb", binary="hexyl"),
    dict(name="dust", description="Intuitive du replacement written in Rust",
         version="latest", category="core", install="deb",
         github="bootandy/dust", asset="x86_64-unknown-linux-musl.tar.gz", binary="dust"),
    dict(name="dua-cli", description="Interactive disk space analyzer",
         version="latest", category="xtra", install="cargo", crate_name="dua-cli",
         github="Byron/dua-cli", binary="dua"),
    dict(name="procs", description="Modern ps replacement written in Rust",
         version="latest", category="core", install="apt", apt_name="procs", binary="procs"),
    dict(name="bottom", description="Cross-platform graphical process monitor (btm)",
         version="latest", category="core", install="deb",
         github="ClementTsang/bottom", asset="x86_64-unknown-linux-musl.tar.gz", binary="btm"),
    dict(name="zenith", description="System monitor with zoom-able charts",
         version="latest", category="xtra", install="cargo", crate_name="zenith",
         github="bvaisvil/zenith", binary="zenith"),
    dict(name="ytop", description="Terminal system monitor (btm predecessor)",
         version="latest", category="xtra", install="cargo", crate_name="ytop",
         github="cjbassi/ytop", binary="ytop"),
    dict(name="starship", description="Cross-shell customizable prompt",
         version="latest", category="core", install="apt", apt_name="starship", binary="starship"),
    dict(name="atuin", description="Magical shell history with sync and search",
         version="latest", category="core", install="apt", apt_name="atuin", binary="atuin"),
    dict(name="nushell", description="Nu shell — structured data shell written in Rust",
         version="latest", category="core", install="github",
         github="nushell/nushell", asset="x86_64-unknown-linux-musl.tar.gz", binary="nu"),
    dict(name="just", description="Command runner and Makefile alternative",
         version="latest", category="core", install="apt", apt_name="just", binary="just"),
    dict(name="xcp", description="Extended cp with progress bars and parallel copy",
         version="latest", category="core", install="cargo", crate_name="xcp",
         github="tarka/xcp", binary="xcp"),
    dict(name="sd", description="Intuitive find & replace CLI (sed alternative)",
         version="latest", category="xtra", install="cargo", crate_name="sd",
         github="chmln/sd", binary="sd"),
    dict(name="sad", description="Space Age seD — find & replace with diff preview",
         version="latest", category="xtra", install="github",
         github="ms-jpq/sad", asset="x86_64-unknown-linux-musl.tar.gz", binary="sad"),
    dict(name="rnr", description="Batch rename tool written in Rust",
         version="latest", category="core", install="github",
         github="ismaelgv/rnr", asset="x86_64-unknown-linux-musl.tar.gz", binary="rnr"),
    dict(name="rip", description="Safe rm replacement with trash/graveyard support",
         version="latest", category="core", install="cargo", crate_name="rm-improved",
         github="nivekuil/rip", binary="rip"),
    dict(name="fuc", description="Modern cp/rm implementations — cpz and rmz",
         version="latest", category="xtra", install="cargo", crate_name="fuc",
         github="SUPERCILEX/fuc", binary="cpz"),
    dict(name="shred-rust", description="Secure file deletion tool in Rust",
         version="latest", category="xtra", install="cargo", crate_name="shred",
         github="JuanJMarques/shred-rust", binary="shred"),
    dict(name="choose", description="Human-friendly cut/awk field selector",
         version="latest", category="xtra", install="cargo", crate_name="choose",
         github="theryangeary/choose", binary="choose"),
    dict(name="hck", description="High-performance cut replacement",
         version="latest", category="xtra", install="cargo", crate_name="hck",
         github="sstadick/hck", binary="hck"),
    dict(name="tokei", description="Count lines of code by language",
         version="latest", category="xtra", install="cargo", crate_name="tokei",
         github="XAMPPRocky/tokei", binary="tokei"),
    dict(name="huniq", description="Remove duplicate lines from stdin (uniq without sorting)",
         version="latest", category="xtra", install="cargo", crate_name="huniq",
         github="koraa/huniq", binary="huniq"),
    dict(name="rargs", description="xargs with pattern matching (like xargs + awk)",
         version="latest", category="xtra", install="cargo", crate_name="rargs",
         github="lotabout/rargs", binary="rargs"),
    dict(name="argc", description="Bash argument parser and command runner",
         version="latest", category="xtra", install="cargo", crate_name="argc",
         github="sigoden/argc", binary="argc"),
    dict(name="stringsext", description="Find multi-byte encoded strings in binary files",
         version="latest", category="xtra", install="cargo", crate_name="stringsext",
         github="getreu/stringsext", binary="stringsext"),
    dict(name="xh", description="Friendly and fast HTTP client (HTTPie alternative)",
         version="latest", category="core", install="github",
         github="ducaale/xh", asset="x86_64-unknown-linux-musl.tar.gz", binary="xh"),
    dict(name="dog", description="User-friendly DNS lookup tool",
         version="latest", category="xtra", install="github",
         github="ogham/dog", asset="x86_64-unknown-linux-musl.tar.gz", binary="dog"),
    dict(name="dqy", description="Modern DNS query tool",
         version="latest", category="xtra", install="cargo", crate_name="dqy",
         github="dandyvica/dqy", binary="dqy"),
    dict(name="json-env", description="Inject JSON values into process environment",
         version="latest", category="xtra", install="cargo", crate_name="json_env",
         github="brodo/json_env", binary="json_env"),
    dict(name="gping", description="Graphical ping with live chart",
         version="latest", category="xtra", install="cargo", crate_name="gping",
         github="orf/gping", binary="gping"),
    dict(name="bandwhich", description="Terminal bandwidth utilization tool",
         version="latest", category="xtra", install="cargo", crate_name="bandwhich",
         github="imsnif/bandwhich", binary="bandwhich"),
    dict(name="trippy", description="Network diagnostic TUI combining traceroute and ping",
         version="latest", category="xtra", install="github",
         github="fujiapple852/trippy", asset="x86_64-unknown-linux-musl.tar.gz", binary="trip"),
    dict(name="netscanner", description="Network scanner TUI",
         version="latest", category="xtra", install="cargo", crate_name="netscanner",
         github="Chleba/netscanner", binary="netscanner"),
    dict(name="impala", description="Wi-Fi management TUI",
         version="latest", category="xtra", install="cargo", crate_name="impala",
         github="pythops/impala", binary="impala"),
    dict(name="vector", description="High-performance observability data pipeline",
         version="latest", category="xtra", install="script",
         url="https://sh.vector.dev", github="vectordotdev/vector", binary="vector"),

    # ── Fuzzy Finders & Search ─────────────────────────────────────────────────
    dict(name="skim", description="Fuzzy finder written in Rust (sk)",
         version="latest", category="core", install="cargo", crate_name="skim",
         github="skim-rs/skim", binary="sk"),
    dict(name="navi", description="Interactive cheatsheet tool for the terminal",
         version="latest", category="core", install="github",
         github="denisidoro/navi", asset="x86_64-unknown-linux-musl.tar.gz", binary="navi"),
    dict(name="tealdeer", description="Fast tldr client in Rust",
         version="latest", category="core", install="apt", apt_name="tealdeer", binary="tldr"),
    dict(name="intelli-shell", description="Fuzzy shell history with bookmarks",
         version="latest", category="xtra", install="cargo", crate_name="intelli-shell",
         github="lasantosr/intelli-shell", binary="intelli-shell"),
    dict(name="television", description="Blazingly fast fuzzy finder TUI",
         version="latest", category="core", install="github",
         github="alexpasmantier/television", asset="x86_64-unknown-linux-musl.tar.gz", binary="tv"),
    dict(name="broot", description="Interactive tree view, fuzzy search, navigate directories",
         version="latest", category="core", install="github",
         github="Canop/broot", asset="x86_64-unknown-linux-musl.tar.gz", binary="broot"),

    # ── Editors ────────────────────────────────────────────────────────────────
    dict(name="helix", description="Post-modern modal text editor",
         version="latest", category="core", install="github",
         github="helix-editor/helix", asset="x86_64-linux.tar.xz", binary="hx"),
    dict(name="kibi", description="Tiny configurable text editor (< 1024 lines of Rust)",
         version="latest", category="core", install="github",
         github="ilai-deutel/kibi", asset="x86_64-unknown-linux-musl.tar.gz", binary="kibi"),
    dict(name="amp", description="Text editor inspired by vim, written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="amp",
         github="jmacdonald/amp", binary="amp"),
    dict(name="ox", description="Fast and lightweight terminal text editor",
         version="latest", category="xtra", install="github",
         github="curlpipe/ox", asset="ox-linux", binary="ox"),
    dict(name="iota", description="A terminal-based text editor written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="iota",
         github="gchp/iota", binary="iota"),
    dict(name="kibi", description="Tiny text editor with syntax highlighting",
         version="latest", category="xtra", install="cargo", crate_name="kibi",
         github="ilai-deutel/kibi", binary="kibi"),

    # ── File Managers ──────────────────────────────────────────────────────────
    dict(name="joshuto", description="Ranger-like terminal file manager written in Rust",
         version="latest", category="core", install="github",
         github="kamiyaa/joshuto", asset="x86_64-unknown-linux-musl.tar.gz", binary="joshuto"),
    dict(name="broot", description="Tree view and directory navigation tool",
         version="latest", category="core", install="github",
         github="Canop/broot", asset="x86_64-unknown-linux-musl.tar.gz", binary="broot"),
    dict(name="spacedrive", description="Open-source cross-platform file explorer",
         version="latest", category="xtra", install="github",
         github="spacedriveapp/spacedrive", asset="x86_64.AppImage", binary="spacedrive"),
    dict(name="tre", description="Tree command reimplemented in Rust with git support",
         version="latest", category="xtra", install="cargo", crate_name="tre-command",
         github="dduan/tre", binary="tre"),
    dict(name="lla", description="Lightning-fast ls alternative with plugins",
         version="latest", category="xtra", install="cargo", crate_name="lla",
         github="chaqchase/lla", binary="lla"),
    dict(name="czkawka", description="Fast duplicate file and folder finder",
         version="latest", category="core", install="github",
         github="qarmin/czkawka", asset="linux_czkawka_cli", binary="czkawka_cli"),

    # ── Shell Tools ────────────────────────────────────────────────────────────
    dict(name="brush", description="Bash-compatible shell implemented in Rust",
         version="latest", category="xtra", install="cargo", crate_name="brush-shell",
         github="reubeno/brush", binary="brush"),
    dict(name="ion", description="Modern Unix shell written in Rust (Redox OS shell)",
         version="latest", category="xtra", install="cargo", crate_name="ion-shell",
         github="redox-os/ion", binary="ion"),
    dict(name="shellharden", description="Bash syntax highlighter and harden tool",
         version="latest", category="xtra", install="cargo", crate_name="shellharden",
         github="anordal/shellharden", binary="shellharden"),

    # ── Git Tools ─────────────────────────────────────────────────────────────
    dict(name="gitui", description="Blazing fast terminal client for git",
         version="latest", category="core", install="github",
         github="extrawurst/gitui", asset="gitui-linux-musl.tar.gz", binary="gitui"),
    dict(name="steer", description="Navigate git history with a TUI",
         version="latest", category="xtra", install="cargo", crate_name="steer",
         github="BrendanGraham14/steer", binary="steer"),
    dict(name="absorb", description="Automatic git fixup commits",
         version="latest", category="xtra", install="cargo", crate_name="git-absorb",
         github="kloki/absorb", binary="git-absorb"),
    dict(name="gptcommit", description="Auto-generate conventional git commit messages with GPT",
         version="latest", category="ai", install="cargo", crate_name="gptcommit",
         github="zurawiki/gptcommit", binary="gptcommit"),

    # ── Terminal Multiplexers ─────────────────────────────────────────────────
    dict(name="zellij", description="Terminal workspace with batteries included",
         version="latest", category="core", install="github",
         github="zellij-org/zellij", asset="x86_64-unknown-linux-musl.tar.gz", binary="zellij"),
    dict(name="mprocs", description="Run multiple commands simultaneously in a TUI",
         version="latest", category="xtra", install="cargo", crate_name="mprocs",
         github="pvolok/mprocs", binary="mprocs"),

    # ── System Monitor / Process ──────────────────────────────────────────────
    dict(name="systeroid", description="Interactive sysctl TUI manager",
         version="latest", category="core", install="github",
         github="orhun/systeroid", asset="x86_64-unknown-linux-musl.tar.gz", binary="systeroid"),
    dict(name="systemctl-tui", description="Simple TUI for systemctl and journalctl",
         version="latest", category="xtra", install="cargo", crate_name="systemctl-tui",
         github="rgwood/systemctl-tui", binary="systemctl-tui"),
    dict(name="systemd-manager-tui", description="TUI for managing systemd services",
         version="latest", category="xtra", install="cargo", crate_name="systemd-manager-tui",
         github="matheus-git/systemd-manager-tui", binary="systemd-manager-tui"),
    dict(name="cpustate-tui", description="CPU state TUI visualizer",
         version="latest", category="xtra", install="cargo", crate_name="cpustate-tui",
         github="mkulke/cpustate-tui", binary="cpustate-tui"),

    # ── Network & HTTP ────────────────────────────────────────────────────────
    dict(name="drill", description="HTTP load testing application written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="drill",
         github="fcsonline/drill", binary="drill"),
    dict(name="rustscan", description="Fast port scanner that finds open ports in seconds",
         version="latest", category="xtra", install="github",
         github="bee-san/RustScan", asset="x86_64-linux.zip", binary="rustscan"),
    dict(name="simple-http-server", description="Simple static HTTP server",
         version="latest", category="xtra", install="cargo", crate_name="simple-http-server",
         github="TheWaWaR/simple-http-server", binary="simple-http-server"),
    dict(name="microbin", description="Tiny, self-hosted, feature-rich paste service",
         version="latest", category="xtra", install="cargo", crate_name="microbin",
         github="szabodanika/microbin", binary="microbin"),

    # ── Language-Specific Tools ───────────────────────────────────────────────
    dict(name="fnm", description="Fast Node.js version manager",
         version="latest", category="core", install="script",
         url="https://fnm.vercel.app/install",
         github="Schniz/fnm", binary="fnm"),
    dict(name="volta", description="JavaScript toolchain manager",
         version="latest", category="core", install="script",
         url="https://get.volta.sh",
         github="volta-cli/volta", binary="volta"),
    dict(name="deno", description="A secure JavaScript and TypeScript runtime",
         version="latest", category="core", install="script",
         url="https://deno.land/install.sh",
         github="denoland/deno", binary="deno"),
    dict(name="swc", description="Super-fast JavaScript/TypeScript compiler",
         version="latest", category="xtra", install="npm", npm_name="@swc/cli",
         github="swc-project/swc", binary="swc"),
    dict(name="dprint", description="Pluggable and configurable code formatting platform",
         version="latest", category="xtra", install="script",
         url="https://dprint.dev/install.sh",
         github="dprint/dprint", binary="dprint"),
    dict(name="ruff", description="Extremely fast Python linter and formatter",
         version="latest", category="core", install="pip", pip_name="ruff",
         github="astral-sh/ruff", binary="ruff"),
    dict(name="thefuck", description="Corrects your previous console command",
         version="latest", category="xtra", install="pip", pip_name="thefuck",
         github="nvbn/thefuck", binary="thefuck"),
    dict(name="frum", description="Ruby version manager written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="frum",
         github="TaKO8Ki/frum", binary="frum"),
    dict(name="frawk", description="Efficient AWK-like data processing language",
         version="latest", category="xtra", install="cargo", crate_name="frawk",
         github="ezrosent/frawk", binary="frawk"),
    dict(name="rustpython", description="Python interpreter written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="rustpython",
         github="RustPython/RustPython", binary="rustpython"),
    dict(name="pixi", description="Fast cross-platform conda-based package manager",
         version="latest", category="core", install="script",
         url="https://pixi.sh/install.sh",
         github="prefix-dev/pixi", binary="pixi"),
    dict(name="cargo-appimage", description="Build AppImages with cargo",
         version="latest", category="xtra", install="cargo", crate_name="cargo-appimage",
         github="StratusFearMe21/cargo-appimage", binary="cargo-appimage"),
    dict(name="cargo-seek", description="Search crates.io from the terminal",
         version="latest", category="xtra", install="cargo", crate_name="cargo-seek",
         github="tareqimbasher/cargo-seek", binary="cargo-seek"),
    dict(name="cargo-ui", description="Graphical user interface for cargo",
         version="latest", category="xtra", install="cargo", crate_name="cargo-ui",
         github="slint-ui/cargo-ui", binary="cargo-ui"),
    dict(name="uutils-coreutils", description="Rust reimplementation of GNU coreutils",
         version="latest", category="core", install="cargo", crate_name="coreutils",
         github="uutils/coreutils", binary="coreutils"),
    dict(name="astral-uv", description="Extremely fast Python package manager by Astral",
         version="latest", category="core", install="script",
         url="https://astral.sh/uv/install.sh",
         github="astral-sh/uv", binary="uv"),

    # ── Data & JSON ────────────────────────────────────────────────────────────
    dict(name="jql", description="JSON query language CLI",
         version="latest", category="xtra", install="cargo", crate_name="jql",
         github="yamafaktory/jql", binary="jql"),
    dict(name="vtracer", description="Convert raster images to SVG vector graphics",
         version="latest", category="xtra", install="cargo", crate_name="vtracer",
         github="visioncortex/vtracer", binary="vtracer"),
    dict(name="otree", description="View JSON/YAML/TOML as a foldable object tree",
         version="latest", category="xtra", install="github",
         github="fioncat/otree", asset="x86_64-unknown-linux-gnu.tar.gz", binary="otree"),
    dict(name="openapi-tui", description="Terminal UI for browsing OpenAPI specs",
         version="latest", category="xtra", install="cargo", crate_name="openapi-tui",
         github="zaghaghi/openapi-tui", binary="openapi-tui"),

    # ── Code Search & Refactoring ─────────────────────────────────────────────
    dict(name="fastmod", description="Fast partial codemod tool",
         version="latest", category="xtra", install="github",
         github="facebookincubator/fastmod", asset="x86_64-unknown-linux-musl.tar.gz", binary="fastmod"),
    dict(name="igrep", description="Interactive grep — search patterns and preview results",
         version="latest", category="xtra", install="cargo", crate_name="igrep",
         github="konradsz/igrep", binary="ig"),
    dict(name="scooter", description="Find and replace across files in a TUI",
         version="latest", category="xtra", install="cargo", crate_name="scooter",
         github="thomasschafer/scooter", binary="scooter"),
    dict(name="serpl", description="TUI search and replace with regex",
         version="latest", category="xtra", install="cargo", crate_name="serpl",
         github="yassinebridi/serpl", binary="serpl"),

    # ── System Utilities ──────────────────────────────────────────────────────
    dict(name="youki", description="Container runtime written in Rust",
         version="latest", category="xtra", install="github",
         github="youki-dev/youki", asset="x86_64_linux.tar.gz", binary="youki"),
    dict(name="appimagetool", description="Create AppImages from AppDir directories",
         version="latest", category="core", install="github",
         github="AppImage/appimagetool", asset="x86_64.AppImage", binary="appimagetool"),
    dict(name="appimageupdate", description="Update AppImages in-place",
         version="latest", category="xtra", install="github",
         github="AppImageCommunity/AppImageUpdate", asset="x86_64.AppImage", binary="AppImageUpdate"),
    dict(name="ripdrag", description="Drag files from and to the terminal",
         version="latest", category="xtra", install="cargo", crate_name="ripdrag",
         github="nik012003/ripdrag", binary="ripdrag"),
    dict(name="cmd-wrapped", description="Find out how much time you spend in the terminal",
         version="latest", category="xtra", install="cargo", crate_name="cmd-wrapped",
         github="YiNNx/cmd-wrapped", binary="cmd-wrapped"),
    dict(name="confetty", description="Confetti fireworks in your terminal",
         version="latest", category="xtra", install="cargo", crate_name="confetty_rs",
         github="Handfish/confetty_rs", binary="confetty"),
    dict(name="topgrade", description="Upgrade everything — apt, cargo, npm, flatpak, etc.",
         version="latest", category="core", install="deb",
         github="topgrade-rs/topgrade", asset="amd64.deb", binary="topgrade"),
    dict(name="soar", description="Distro-agnostic package manager (SAB format)",
         version="latest", category="core", install="script",
         url="https://raw.githubusercontent.com/pkgforge/soar/main/install.sh",
         github="pkgforge/soar", binary="soar"),
    dict(name="pacstall", description="AUR-inspired package manager for Ubuntu",
         version="latest", category="core", install="script",
         url="https://pacstall.dev/q/install",
         github="pacstall/pacstall", binary="pacstall"),
    dict(name="doxx", description="Documentation tool for shell scripts",
         version="latest", category="xtra", install="cargo", crate_name="doxx",
         github="bgreenwell/doxx", binary="doxx"),
    dict(name="cpc", description="Terminal calculator and currency/unit converter",
         version="latest", category="xtra", install="cargo", crate_name="cpc",
         github="probablykasper/cpc", binary="cpc"),
    dict(name="fresh", description="A file watcher with automatic restarts",
         version="latest", category="xtra", install="cargo", crate_name="fresh",
         github="sinelaw/fresh", binary="fresh"),
    dict(name="weathr", description="Terminal weather app",
         version="latest", category="xtra", install="cargo", crate_name="weathr",
         github="Veirt/weathr", binary="weathr"),

    # ── AI / LLM Tools ────────────────────────────────────────────────────────
    dict(name="aichat", description="All-in-one AI CLI tool with RAG and agents",
         version="latest", category="ai", install="cargo", crate_name="aichat",
         github="sigoden/aichat", binary="aichat"),
    dict(name="tenere", description="TUI interface for LLMs written in Rust",
         version="latest", category="ai", install="cargo", crate_name="tenere",
         github="pythops/tenere", binary="tenere"),
    dict(name="oatmeal", description="Terminal UI for LLMs with model switching",
         version="latest", category="ai", install="github",
         github="dustinblackman/oatmeal", asset="linux_x86_64.tar.gz", binary="oatmeal"),
    dict(name="ironclaw", description="CLI agent framework from NEAR AI",
         version="latest", category="ai", install="script",
         url="https://github.com/nearai/ironclaw/releases/download/ironclaw-v0.29.1/ironclaw-installer.sh",
         github="nearai/ironclaw", binary="ironclaw"),
    dict(name="gemini-cli", description="Google Gemini CLI — AI assistant in the terminal",
         version="latest", category="ai", install="npm", npm_name="@google/gemini-cli",
         github="google-gemini/gemini-cli", binary="gemini"),
    dict(name="open-interpreter", description="Local AI agent that can execute code",
         version="latest", category="ai", install="pip", pip_name="open-interpreter",
         github="OpenInterpreter/open-interpreter", binary="interpreter"),
    dict(name="bashsenpai", description="Terminal AI assistant for bash commands",
         version="latest", category="ai", install="pip", pip_name="bashsenpai",
         github="BashSenpai/cli", binary="bashsenpai"),
    dict(name="xinfer", description="AI inference CLI",
         version="latest", category="ai", install="npm", npm_name="xinfer-ai",
         github="guoqingbao/xinfer", binary="xinfer"),
    dict(name="llmfit", description="LLM fine-tuning tool",
         version="latest", category="ai", install="cargo", crate_name="llmfit",
         github="AlexsJones/llmfit", binary="llmfit"),
    dict(name="llm-chain", description="Rust library for building LLM applications",
         version="latest", category="ai", install="cargo", crate_name="llm-chain-openai",
         github="sobelio/llm-chain", binary="llm"),
    dict(name="clerk", description="Terminal note-taking tool",
         version="latest", category="xtra", install="cargo", crate_name="clerk",
         github="blankenshipz/clerk", binary="clerk"),
    dict(name="fireside-chat", description="GGUF local LLM chat with COSMIC/GTK interface",
         version="latest", category="ai", install="github",
         github="danielclough/fireside-chat", asset="x86_64.AppImage", binary="fireside-chat"),
    dict(name="con-terminal", description="AI-powered terminal by nowledge",
         version="0.1.0-beta.77", category="ai", install="tarball",
         url="https://github.com/nowledge-co/con-terminal/releases/download/v0.1.0-beta.77/con-0.1.0-beta.77-linux-x86_64.tar.gz",
         github="nowledge-co/con-terminal", binary="con"),
    dict(name="kalosm", description="Local AI model runtime — speech, text, images",
         version="latest", category="ai", install="cargo", crate_name="kalosm",
         github="floneum/kalosm", binary="kalosm"),

    # ── Media / Viewers ────────────────────────────────────────────────────────
    dict(name="madamiru", description="Media player with multi-pane grid view",
         version="latest", category="xtra", install="github",
         github="mtkennerly/madamiru", asset="x86_64-unknown-linux-musl.tar.gz", binary="madamiru"),
    dict(name="image-roll", description="Simple and fast GTK image viewer",
         version="latest", category="xtra", install="cargo", crate_name="image-roll",
         github="weclaw1/image-roll", binary="image-roll"),
    dict(name="tts-tui", description="TUI frontend for text-to-speech",
         version="latest", category="xtra", install="cargo", crate_name="tts-tui",
         github="lesleyrs/tts-tui", binary="tts-tui"),
    dict(name="vle", description="Video editor written in Rust",
         version="latest", category="xtra", install="cargo", crate_name="vle",
         github="tuffy/vle", binary="vle"),

    # ── Themes & Desktop ──────────────────────────────────────────────────────
    dict(name="reversal-icon-theme", description="Reversal icon theme with vivid colors",
         version="latest", category="themes", install="git",
         url="https://github.com/yeyushengfan258/Reversal-icon-theme.git",
         github="yeyushengfan258/Reversal-icon-theme",
         install_cmd="bash install.sh -a -d /usr/share/icons"),
    dict(name="fluent-icon-theme", description="Fluent icon theme by vinceliuice",
         version="latest", category="themes", install="git",
         url="https://github.com/vinceliuice/Fluent-icon-theme.git",
         github="vinceliuice/Fluent-icon-theme",
         install_cmd="bash install.sh -d /usr/share/icons"),
    dict(name="la-capitaine-icon-theme", description="La Capitaine icon theme",
         version="latest", category="themes", install="git",
         url="https://github.com/keeferrourke/la-capitaine-icon-theme.git",
         github="keeferrourke/la-capitaine-icon-theme",
         install_cmd="cp -r . /usr/share/icons/la-capitaine"),
    dict(name="qogir-icon-theme", description="Qogir icon theme — flat and colorful",
         version="latest", category="themes", install="git",
         url="https://github.com/vinceliuice/Qogir-icon-theme.git",
         github="vinceliuice/Qogir-icon-theme",
         install_cmd="bash install.sh -d /usr/share/icons"),
    dict(name="tela-icon-theme", description="Tela circle icon theme",
         version="latest", category="themes", install="git",
         url="https://github.com/vinceliuice/Tela-icon-theme.git",
         github="vinceliuice/Tela-icon-theme",
         install_cmd="bash install.sh -a -d /usr/share/icons"),
    dict(name="whitesur-icon-theme", description="WhiteSur icon theme — macOS-like",
         version="latest", category="themes", install="git",
         url="https://github.com/vinceliuice/WhiteSur-icon-theme.git",
         github="vinceliuice/WhiteSur-icon-theme",
         install_cmd="bash install.sh -d /usr/share/icons"),
    dict(name="cosmic-uniform-glass-theme",
         description="Frosted glass theme for COSMIC Desktop",
         version="latest", category="desktop", install="git",
         url="https://github.com/xarbit/cosmic-uniform-glass-theme.git",
         github="xarbit/cosmic-uniform-glass-theme",
         install_cmd="mkdir -p /usr/share/cosmic/themes && cp -r . /usr/share/cosmic/themes/cosmic-uniform-glass-theme"),
    dict(name="simplemoji", description="COSMIC/GTK emoji picker",
         version="latest", category="desktop", install="script",
         url="https://github.com/SergioRibera/Simplemoji/releases/download/v1.2.4/simplemoji-installer.sh",
         github="SergioRibera/Simplemoji", binary="simplemoji"),

    # ── COSMIC Desktop Extras ─────────────────────────────────────────────────
    dict(name="cosmic-connect", description="COSMIC Connect — KDE Connect integration applet",
         version="latest", category="desktop", install="git",
         url="https://github.com/BlancoBAM/cosmic-connect.git",
         github="BlancoBAM/cosmic-connect",
         install_cmd="just install"),
    dict(name="cosmic-clipboard-manager", description="COSMIC Clipboard Manager applet",
         version="latest", category="desktop", install="cargo",
         github="cosmic-utils/clipboard-manager", binary="cosmic-clipboard-manager"),
    dict(name="cosmic-color-picker", description="COSMIC Color Picker utility",
         version="latest", category="desktop", install="cargo",
         github="PixelDoted/cosmic-color-picker", binary="cosmic-color-picker"),
    dict(name="cosmicding", description="Linkding bookmarks client for COSMIC Desktop",
         version="latest", category="desktop", install="cargo", crate_name="cosmicding",
         github="vkhitrin/cosmicding", binary="cosmicding"),
    dict(name="cosmic-forecast", description="Weather app for COSMIC Desktop",
         version="latest", category="desktop", install="cargo",
         github="cosmic-utils/forecast", binary="cosmic-forecast"),
    dict(name="cosmic-app-hub", description="COSMIC App Hub — discover and install COSMIC apps",
         version="latest", category="desktop", install="cargo",
         github="cosmic-utils/app-hub", binary="cosmic-app-hub"),
    dict(name="noctua", description="Dark mode browser dashboard for COSMIC Desktop",
         version="latest", category="desktop", install="cargo",
         github="cosmic-utils/noctua", binary="noctua"),

    # ── Applications ──────────────────────────────────────────────────────────
    dict(name="hellfire", description="HellFire Browser — privacy-focused Firefox fork",
         version="152.0a1", category="core", install="tarball",
         url="https://github.com/CYFARE/HellFire/releases/download/v152.0a1_FP2/hellfire-152.0a1.en-US.linux-x86_64.tar.xz",
         github="CYFARE/HellFire", binary="firefox"),
    dict(name="waveterm", description="Open-source AI-native terminal with visual blocks",
         version="latest", category="xtra", install="github",
         github="wavetermdev/waveterm", asset="amd64.deb", binary="waveterm"),
    dict(name="ferdium", description="All-in-one messaging and service desktop app",
         version="latest", category="xtra", install="appimage",
         url="https://github.com/ferdium/ferdium-app/releases/download/v7.1.2/Ferdium-linux-Portable-7.1.2-x86_64.AppImage",
         github="ferdium/ferdium-app", binary="ferdium"),
    dict(name="furtherance", description="Time tracker app",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="com.lakoliu.Furtherance",
         github="unobserved-io/Furtherance", binary="furtherance"),
    dict(name="vicinae", description="Vicinae Visual Workspace",
         version="latest", category="xtra", install="appimage",
         url="https://github.com/vicinaehq/vicinae/releases/download/v0.21.0/Vicinae-x86_64.AppImage",
         github="vicinaehq/vicinae", binary="vicinae"),
    dict(name="spacedrive", description="Open-source cross-platform file manager",
         version="latest", category="xtra", install="github",
         github="spacedriveapp/spacedrive", asset="Spacedrive-app-x86_64.AppImage", binary="spacedrive"),
    dict(name="keygeist", description="SSH agent UI manager",
         version="latest", category="xtra", install="cargo", crate_name="keygeist",
         github="mudler/Keygeist", binary="keygeist"),
    dict(name="linuxtoys", description="Collection of interactive terminal toys",
         version="latest", category="xtra", install="git",
         url="https://github.com/psygreg/linuxtoys.git",
         github="psygreg/linuxtoys",
         install_cmd="bash install.sh 2>/dev/null || true"),
    dict(name="script-kit", description="Script Kit — automate anything with JavaScript",
         version="latest", category="xtra", install="appimage",
         url="https://github.com/johnlindquist/kit/releases/download/v3.45.1/Script-Kit-Linux-3.45.1-x86_64.AppImage",
         github="johnlindquist/kit", binary="kit"),
    dict(name="telescope", description="Fuzzy-finder, picker, and navigator",
         version="latest", category="xtra", install="cargo", crate_name="telescope",
         github="alexpasmantier/television", binary="tv"),
    dict(name="splashboard", description="Customizable launch screen / dashboard",
         version="latest", category="xtra", install="cargo", crate_name="splashboard",
         github="unhappychoice/splashboard", binary="splashboard"),

    # ── Fonts ─────────────────────────────────────────────────────────────────
    dict(name="noto-color-emoji", description="Noto Color Emoji font",
         version="latest", category="core", install="apt", apt_name="fonts-noto-color-emoji"),

    # ── Flatpak Apps (from Offerings curated list) ────────────────────────────
    dict(name="espanso-gui", description="Graphical frontend for the Espanso text expander",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="io.unobserved.espansoGUI"),
    dict(name="lotti", description="System indicator and journal widget app",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="com.matthiasn.lotti"),
    dict(name="brief", description="Distraction-free markdown writing app",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="io.github.shonebinu.Brief"),
    dict(name="wonderpen", description="Professional writing editor",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="com.tominlab.wonderpen"),
    dict(name="digikam", description="Professional photo asset management",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="org.kde.digikam"),
    dict(name="planify", description="Task management and to-do app",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="io.github.alainm23.planify"),
    dict(name="proton-mail", description="End-to-end encrypted email client",
         version="latest", category="xtra", install="flatpak",
         flatpak_id="me.proton.Mail"),
    dict(name="warp", description="Warp AI-native terminal for Linux",
         version="latest", category="xtra", install="deb",
         url="https://app.warp.dev/download?package=deb",
         github="warpdotdev/warp", binary="warp"),
]


def escape_toml_string(s):
    """Escape a string for TOML double-quoted format."""
    return s.replace('\\', '\\\\').replace('"', '\\"')


def render_packages_toml(packages):
    lines = [
        "# Lilith Linux Package Registry",
        "# URL: https://blancobam.github.io/lilith-packages/packages.toml",
        "# Format consumed by s8n — do not edit manually, use generate-packages-toml.py",
        f"# Packages: {len(packages)}",
        "",
        "[meta]",
        'name    = "Lilith Linux Packages"',
        'version = "2"',
        f'updated = "2026-07-04"',
        "",
        "# install types:",
        "#   deb      → download .deb from url, sudo dpkg -i",
        "#   cargo    → cargo install crate_name",
        "#   github   → fetch latest release from github matching asset pattern",
        "#   appimage → download AppImage, chmod +x, symlink binary",
        "#   tarball  → download tarball, extract binary",
        "#   binary   → download binary directly",
        "#   script   → curl url | sh",
        "#   git      → git clone url, run install_cmd",
        "#   npm      → npm install -g npm_name",
        "#   pip      → pip3 install pip_name",
        "#   apt      → sudo apt install apt_name",
        "#   flatpak  → flatpak install flathub flatpak_id",
        "",
    ]

    seen = set()
    for pkg in packages:
        name = pkg["name"]
        if name in seen:
            continue
        seen.add(name)

        lines.append("[[packages]]")
        lines.append(f'name        = "{escape_toml_string(name)}"')
        lines.append(f'description = "{escape_toml_string(pkg.get("description", ""))}"')
        lines.append(f'version     = "{escape_toml_string(pkg.get("version", "latest"))}"')
        lines.append(f'category    = "{escape_toml_string(pkg.get("category", "xtra"))}"')
        lines.append(f'install     = "{escape_toml_string(pkg.get("install", "cargo"))}"')

        for field in ["url", "github", "asset", "binary", "crate_name",
                      "npm_name", "pip_name", "apt_name", "flatpak_id", "install_cmd"]:
            val = pkg.get(field, "")
            if val:
                lines.append(f'{field:12s}= "{escape_toml_string(val)}"')

        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    print(render_packages_toml(PACKAGES))
